name: Feature Request
description: Suggest improvements
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A detailed description of a feature or an improvement you would like to see.
    validations:
      required: true
    
  - type: textarea
    id: how-it-works
    attributes:
      label: Technical Details
      description: Describe how this feature would work. Include any relevant technical details.
    validations:
      required: true
    
  - type: textarea
    id: existing-implementations
    attributes:
      label: Existing Implementations
      description: List at least one program with that feature. Provide examples.
    validations:
      required: true
