name: Test

on:
  push:
    branches:

  pull_request:

jobs:
  test:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: |
        make venv-dev
        source env_dev/bin/activate
    - name: Run tests
      run: pytest tests/
    - name: Run slow tests
      run: make test-slowest
    - name: Run coverage
      run: make coverage
